name: task_management
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  auto_route: ^3.2.4
  easy_localization: ^3.0.0
  boardview: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10

flutter:

  uses-material-design: true

  assets:
    - assets/languages/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato.ttf
        
    - family: AppIcons
      fonts:
        - asset: assets/fonts/icons.ttf
  